# Generate monocular depth maps for the Cosmic Landmarks volumetric exhibits.
#
# The landmark photographs carry no true depth; this tool infers per-pixel
# relative depth with Depth-Anything-V2-Small (offline, one-time) and writes:
#   images/depth/<id>.png      grayscale, brighter = closer, max 384px
#   js/data/landmarkDepth.js   manifest consumed by js/procgen/exhibits.js
#
# Run from the repo root (downloads ~100 MB model on first use):
#   uv run --with torch --with transformers --with pillow tools/generate_depth.py
#   uv run --with torch --with transformers --with pillow tools/generate_depth.py rosette-nebula trifid-nebula
#
# Only landmarks whose category renders as a volume (NEBULA / SUPERNOVA /
# GALAXY) are processed.

import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VOLUME_CATEGORIES = {"NEBULA", "SUPERNOVA", "GALAXY"}

def parse_catalog():
    lm = (ROOT / "js/data/landmarks.js").read_text()
    cats = dict(re.findall(r'id:\s*"([^"]+)".*?category:\s*"([^"]+)"', lm, re.S))
    im = (ROOT / "js/data/landmarkImages.js").read_text()
    files = dict(re.findall(r"'([^']+)':\s*\{\s*file:\s*I\s*\+\s*'([^']+)'", im))
    return [(i, ROOT / "images" / f) for i, f in files.items()
            if cats.get(i) in VOLUME_CATEGORIES]

def main():
    from PIL import Image
    from transformers import pipeline

    requested = set(sys.argv[1:])
    all_targets = parse_catalog()
    known = {lid for lid, _ in all_targets}
    unknown = sorted(requested - known)
    if unknown:
        raise SystemExit(f"unknown landmark id(s): {', '.join(unknown)}")
    targets = [(lid, path) for lid, path in all_targets
               if not requested or lid in requested]
    print(f"{len(targets)} landmark images to process")
    out_dir = ROOT / "images/depth"
    out_dir.mkdir(exist_ok=True)

    pipe = pipeline("depth-estimation",
                    model="depth-anything/Depth-Anything-V2-Small-hf")

    done = []
    for i, (lid, path) in enumerate(targets):
        if not path.exists():
            print(f"  !! missing {path.name}, skipped"); continue
        img = Image.open(path).convert("RGB")
        depth = pipe(img)["depth"]                     # PIL, brighter = closer
        lo, hi = depth.getextrema()
        if hi > lo:                                    # normalize to full range
            depth = depth.point(lambda v: int((v - lo) * 255 / (hi - lo)))
        depth = depth.convert("L")
        depth.thumbnail((384, 384), Image.LANCZOS)
        depth.save(out_dir / f"{lid}.png", optimize=True)
        done.append(lid)
        print(f"  [{i+1}/{len(targets)}] {lid} ({depth.size[0]}x{depth.size[1]})")

    if requested:
        print(f"updated {len(done)} selected depth map(s); manifest unchanged")
        return

    entries = "\n".join(f"  '{lid}': D + '{lid}.png'," for lid in done)
    (ROOT / "js/data/landmarkDepth.js").write_text(f"""/* GENERATED by tools/generate_depth.py (Depth-Anything-V2-Small).
   Monocular depth maps for volumetric landmark exhibits — brighter = closer.
   Regenerate with:
   uv run --with torch --with transformers --with pillow tools/generate_depth.py */

const D = 'images/depth/';

export const LANDMARK_DEPTH = {{
{entries}
}};

export function landmarkDepth(id){{ return LANDMARK_DEPTH[id] || null; }}
""")
    print(f"wrote {len(done)} depth maps + js/data/landmarkDepth.js")

if __name__ == "__main__":
    sys.exit(main())
